Add SPbUnited info
robocup-ssl-br/adm-team-brands pull request #9
Opened 2024-05-11 19:08 UTC by AlexM-dev

2024-05-21 11:25 UTC, FelipeGdM requested changes
A small adjustment is needed in the README.md

2024-05-21 11:25 UTC, FelipeGdM commented on spbunited/README.md
> +### Team information
```suggestion
## Team information
```

2024-05-22 17:09 UTC, FelipeGdM approved these changes

2024-11-21 17:48 UTC, lhcavalcanti approved these changes

2024-11-21 17:51 UTC, merged